spring.application.name=investment-operations
spring.datasource.url=jdbc:postgresql://localhost:5432/investment_operations
spring.datasource.username=postgres
spring.datasource.password=Jay@123

spring.jpa.hibernate.ddl-auto=update
